apiVersion: v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/name: envbox-smoke
    experiment.coder.com/cache-mount: prototype
    experiment.coder.com/role: workspace
  name: envbox-smoke
  namespace: envbox-auto
spec:
  containers:
  - command:
    - /envbox
    - docker
    env:
    - name: CODER_INNER_IMAGE
      value: us-docker.pkg.dev/coder-v2-images-public/public/envbox/enterprise-base@sha256:770f0a4fc1f2f730ad3f9096a13e86e356e2d1f9c4c5081918d23623d578d72d
    - name: CODER_INNER_IMAGE_CACHE_DIR
      value: /cache
    - name: CODER_INNER_USERNAME
      value: coder
    - name: CODER_INNER_HOSTNAME
      value: envbox-smoke
    - name: CODER_MOUNTS
      value: /home/coder:/home/coder
    - name: CODER_CPUS
      value: "1"
    - name: CODER_MEMORY
      value: "4294967296"
    - name: CODER_DEBUG
      value: "true"
    image: 849808308023.dkr.ecr.us-east-2.amazonaws.com/envbox-eks-cache-experiment@sha256:f48bb6494552adeaeb4f0ffa0c8aa01b74ba93665a5554efc8f000ff4b3fdf62
    imagePullPolicy: Always
    name: envbox
    resources:
      limits:
        cpu: "2"
        memory: 7Gi
      requests:
        cpu: "1"
        memory: 3Gi
    securityContext:
      allowPrivilegeEscalation: true
      privileged: true
      seccompProfile:
        type: Unconfined
    volumeMounts:
    - mountPath: /home/coder
      name: workspace
      subPath: home
    - mountPath: /var/lib/coder/docker
      name: workspace
      subPath: cache/docker
    - mountPath: /var/lib/coder/containers
      name: workspace
      subPath: cache/containers
    - mountPath: /var/lib/sysbox
      name: sysbox
    - mountPath: /var/lib/containers
      name: workspace
      subPath: envbox-cache-hit/containers
    - mountPath: /var/lib/docker
      name: workspace
      subPath: envbox-cache-hit/docker
    - mountPath: /usr/src
      name: usr-src
      readOnly: true
    - mountPath: /lib/modules
      name: lib-modules
      readOnly: true
    - mountPath: /cache
      name: cache
  hostAliases:
  - hostnames:
    - us-docker.pkg.dev
    ip: 127.0.0.1
  initContainers:
  - command:
    - /bin/sh
    - -ec
    - |-
      mkdir -p \
        /workspace-volume/home \
        /workspace-volume/cache/docker \
        /workspace-volume/cache/containers \
        /workspace-volume/envbox-cache-hit/containers \
        /workspace-volume/envbox-cache-hit/docker
    image: public.ecr.aws/docker/library/alpine:3.21
    imagePullPolicy: IfNotPresent
    name: initialize-workspace-volume
    resources:
      limits:
        memory: 64Mi
      requests:
        cpu: 10m
        memory: 16Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsGroup: 0
      runAsUser: 0
      seccompProfile:
        type: RuntimeDefault
    volumeMounts:
    - mountPath: /workspace-volume
      name: workspace
  nodeSelector:
    experiment.coder.com/envbox-auto: "true"
  restartPolicy: Never
  terminationGracePeriodSeconds: 300
  tolerations:
  - effect: NoSchedule
    key: experiment.coder.com/envbox-auto
    operator: Equal
    value: "true"
  volumes:
  - name: workspace
    persistentVolumeClaim:
      claimName: envbox-workspace
  - emptyDir: {}
    name: sysbox
  - hostPath:
      path: /usr/src
      type: ""
    name: usr-src
  - hostPath:
      path: /lib/modules
      type: ""
    name: lib-modules
  - hostPath:
      path: /var/lib/envbox-image-cache
      type: DirectoryOrCreate
    name: cache
