apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: nested-virt
spec:
  template:
    metadata:
      labels:
        workload: nested-virt
    spec:
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: default

      taints:
        - key: workload
          value: nested-virt
          effect: NoSchedule

      requirements:
        - key: node.kubernetes.io/instance-type
          operator: In
          values:
            - c8i.2xlarge
        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - on-demand
