apiVersion: v1
kind: Pod
metadata:
  name: nested-virt-trigger
spec:
  restartPolicy: Never
  nodeSelector:
    workload: nested-virt
  tolerations:
    - key: workload
      value: nested-virt
      effect: NoSchedule
  containers:
    - name: trigger
      image: public.ecr.aws/amazonlinux/amazonlinux:2023
      command: ["/bin/bash", "-c"]
      args: ["sleep 3600"]
      resources:
        requests:
          cpu: "2"
          memory: 2Gi
        limits:
          cpu: "2"
          memory: 2Gi
