apiVersion: v1
kind: Namespace
metadata:
  name: direct-sysbox
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workspace-docker
  namespace: direct-sysbox
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: direct-sysbox-gp3
  resources:
    requests:
      storage: 30Gi
