apiVersion: v1
kind: Pod
metadata:
  name: direct-sysbox-workspace
  namespace: direct-sysbox
  labels:
    app.kubernetes.io/name: direct-sysbox-workspace
spec:
  runtimeClassName: sysbox-runc
  hostUsers: false
  restartPolicy: Never
  nodeSelector:
    experiment.coder.com/direct-sysbox: "true"
  containers:
    - name: workspace
      image: registry.nestybox.com/nestybox/ubuntu-focal-systemd-docker@sha256:e451ce586ea5c0224c511d4c87b9aa215173db0d1eac6473d0e4b3b5abe41ba5
      imagePullPolicy: Always
      command:
        - /sbin/init
      securityContext:
        privileged: false
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        seccompProfile:
          type: RuntimeDefault
      resources:
        requests:
          cpu: "1"
          memory: 2Gi
        limits:
          cpu: "2"
          memory: 6Gi
      volumeMounts:
        - name: docker-data
          mountPath: /var/lib/docker
  volumes:
    - name: docker-data
      persistentVolumeClaim:
        claimName: workspace-docker
