apiVersion: v1
kind: Node
metadata:
  annotations:
    alpha.kubernetes.io/provided-node-ip: 192.168.131.224
    csi.volume.kubernetes.io/nodeid: '{"ebs.csi.eks.amazonaws.com":"i-0c1011a1ef58147da"}'
    eks.amazonaws.com/ca-bundle-hash: "17054071131196745078"
    eks.amazonaws.com/kubelet-version: "1.36"
    eks.amazonaws.com/nodeclass-hash: "11235578445154985766"
    eks.amazonaws.com/nodeclass-hash-version: v2
    karpenter.sh/nodeclaim-min-values-relaxed: "false"
    karpenter.sh/nodepool-hash: "3936462471767995178"
    karpenter.sh/nodepool-hash-version: v3
    node.alpha.kubernetes.io/ttl: "0"
    volumes.kubernetes.io/controller-managed-attach-detach: "true"
  creationTimestamp: "2026-08-06T22:44:47Z"
  finalizers:
  - karpenter.sh/termination
  labels:
    app.kubernetes.io/managed-by: eks
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/instance-type: m6i.large
    beta.kubernetes.io/os: linux
    eks.amazonaws.com/compute-type: auto
    eks.amazonaws.com/instance-capability-flex: "false"
    eks.amazonaws.com/instance-category: m
    eks.amazonaws.com/instance-cpu: "2"
    eks.amazonaws.com/instance-cpu-manufacturer: intel
    eks.amazonaws.com/instance-cpu-sustained-clock-speed-mhz: "3500"
    eks.amazonaws.com/instance-ebs-bandwidth: "10000"
    eks.amazonaws.com/instance-encryption-in-transit-supported: "true"
    eks.amazonaws.com/instance-family: m6i
    eks.amazonaws.com/instance-generation: "6"
    eks.amazonaws.com/instance-hypervisor: nitro
    eks.amazonaws.com/instance-memory: "8192"
    eks.amazonaws.com/instance-network-bandwidth: "781"
    eks.amazonaws.com/instance-size: large
    eks.amazonaws.com/nitro-sandbox: "false"
    eks.amazonaws.com/nodeclass: default
    experiment.coder.com/userns-dind-auto-prepped: "true"
    experiment.coder.com/userns-ready: "true"
    failure-domain.beta.kubernetes.io/region: us-east-2
    failure-domain.beta.kubernetes.io/zone: us-east-2c
    k8s.io/cloud-provider-aws: 4738d681aad46db24e43eb06a93d1a50
    karpenter.k8s.aws/instance-tenancy: default
    karpenter.sh/capacity-type: on-demand
    karpenter.sh/do-not-sync-taints: "true"
    karpenter.sh/initialized: "true"
    karpenter.sh/nodepool: userns-dind-auto-prepped
    karpenter.sh/registered: "true"
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: i-0c1011a1ef58147da
    kubernetes.io/os: linux
    node.kubernetes.io/instance-type: m6i.large
    topology.ebs.csi.eks.amazonaws.com/zone: us-east-2c
    topology.k8s.aws/zone-id: use2-az3
    topology.kubernetes.io/region: us-east-2
    topology.kubernetes.io/zone: us-east-2c
  name: i-0c1011a1ef58147da
  ownerReferences:
  - apiVersion: karpenter.sh/v1
    blockOwnerDeletion: true
    kind: NodeClaim
    name: userns-dind-auto-prepped-q52mv
    uid: 4afae69f-8b49-4577-868e-cd4b23b4c6d8
  resourceVersion: "43793"
  uid: b4060a2b-0e3f-419e-8804-ca709ccff50f
spec:
  providerID: aws:///us-east-2c/i-0c1011a1ef58147da
  taints:
  - effect: NoSchedule
    key: experiment.coder.com/userns-dind-auto
    value: "true"
status:
  addresses:
  - address: 192.168.131.224
    type: InternalIP
  - address: ip-192-168-131-224.us-east-2.compute.internal
    type: InternalDNS
  - address: ip-192-168-131-224.us-east-2.compute.internal
    type: Hostname
  allocatable:
    cpu: 1780m
    ephemeral-storage: "76173383962"
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 7219612Ki
    pods: "27"
  capacity:
    cpu: "2"
    ephemeral-storage: 81854Mi
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 7964060Ki
    pods: "27"
  conditions:
  - lastHeartbeatTime: "2026-08-06T23:13:50Z"
    lastTransitionTime: "2026-08-06T22:44:47Z"
    message: kubelet has sufficient memory available
    reason: KubeletHasSufficientMemory
    status: "False"
    type: MemoryPressure
  - lastHeartbeatTime: "2026-08-06T23:13:50Z"
    lastTransitionTime: "2026-08-06T22:44:47Z"
    message: kubelet has no disk pressure
    reason: KubeletHasNoDiskPressure
    status: "False"
    type: DiskPressure
  - lastHeartbeatTime: "2026-08-06T23:13:50Z"
    lastTransitionTime: "2026-08-06T22:44:47Z"
    message: kubelet has sufficient PID available
    reason: KubeletHasSufficientPID
    status: "False"
    type: PIDPressure
  - lastHeartbeatTime: "2026-08-06T23:13:50Z"
    lastTransitionTime: "2026-08-06T22:44:48Z"
    message: kubelet is posting ready status
    reason: KubeletReady
    status: "True"
    type: Ready
  - lastHeartbeatTime: "2026-08-06T23:14:47Z"
    lastTransitionTime: "2026-08-06T22:44:47Z"
    message: Monitoring for the ContainerRuntime system is active
    reason: ContainerRuntimeIsReady
    status: "True"
    type: ContainerRuntimeReady
  - lastHeartbeatTime: "2026-08-06T23:14:47Z"
    lastTransitionTime: "2026-08-06T22:44:47Z"
    message: Monitoring for the Networking system is active
    reason: NetworkingIsReady
    status: "True"
    type: NetworkingReady
  - lastHeartbeatTime: "2026-08-06T23:14:47Z"
    lastTransitionTime: "2026-08-06T22:44:47Z"
    message: Monitoring for the Kernel system is active
    reason: KernelIsReady
    status: "True"
    type: KernelReady
  - lastHeartbeatTime: "2026-08-06T23:14:47Z"
    lastTransitionTime: "2026-08-06T22:44:47Z"
    message: Monitoring for the Disk system is active
    reason: DiskIsReady
    status: "True"
    type: StorageReady
  daemonEndpoints:
    kubeletEndpoint:
      Port: 10250
  declaredFeatures:
  - ExtendWebSocketsToKubelet
  - InPlacePodLevelResourcesVerticalScaling
  - InPlacePodVerticalScalingInitContainers
  - RestartAllContainersOnContainerExits
  features:
    supplementalGroupsPolicy: true
  images:
  - names:
    - public.ecr.aws/docker/library/golang@sha256:8bee1901f1e530bfb4a7850aa7a479d17ae3a18beb6e09064ed54cfd245b7191
    - public.ecr.aws/docker/library/golang:1.24-alpine
    sizeBytes: 83301112
  - names:
    - public.ecr.aws/docker/library/alpine@sha256:48b0309ca019d89d40f670aa1bc06e426dc0931948452e8491e3d65087abc07d
    - public.ecr.aws/docker/library/alpine:3.21
    sizeBytes: 3657726
  - names:
    - localhost/kubernetes/pause:0.1.0
    sizeBytes: 92951
  nodeInfo:
    architecture: amd64
    bootID: a122958d-132d-4dce-9eb0-fdbed66f3e08
    containerRuntimeVersion: containerd://2.2.5+bottlerocket
    kernelVersion: 6.18.38
    kubeProxyVersion: ""
    kubeletVersion: v1.36.1-eks-a3a0722
    machineID: ec2a3ee18e880b6369d0a8762ed2a747
    operatingSystem: linux
    osImage: Bottlerocket (EKS Auto, Standard) 2026.8.3 (aws-k8s-1.36-standard)
    swap:
      capacity: 1073737728
    systemUUID: ec2a3ee1-8e88-0b63-69d0-a8762ed2a747
  runtimeHandlers:
  - features:
      recursiveReadOnlyMounts: true
      userNamespaces: true
    name: ""
  - features:
      recursiveReadOnlyMounts: true
      userNamespaces: true
    name: runc
