apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workspace-data-cgroup-writable
  namespace: userns-rootful-dind
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: gp3-csi
  resources:
    requests:
      storage: 30Gi
