apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: nested-virt-mng-136
  region: us-east-2
managedNodeGroups:
  - name: nested-virt-mng
    amiFamily: AmazonLinux2023
    desiredCapacity: 1
    minSize: 1
    maxSize: 1
    launchTemplate:
      id: lt-013959302183b2415
      version: "1"
    labels:
      workload: nested-virt
    taints:
      - key: workload
        value: nested-virt
        effect: NoSchedule
