name: promote-latest

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "The tag to point latest to"
        required: true

permissions:
  actions: read
  checks: none
  contents: write
  deployments: none
  issues: none
  packages: write
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  manifest:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.tag }}
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Manifest
        run: |
          docker manifest create ghcr.io/coder/envbox:latest \
            --amend ghcr.io/coder/envbox:${{ github.event.inputs.tag }}-amd64 \
            --amend ghcr.io/coder/envbox:${{ github.event.inputs.tag }}-arm64

      - name: Push Manifest
        run: |
          docker manifest push ghcr.io/coder/envbox:latest
